dist: xenial

language: rust

services:
    - docker

before_install:
    - docker -v
    - docker build --rm -t zboxfs/wasm .
    - docker images

script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push zboxfs/wasm

notifications:
    email:
        on_success: never
